-- ===== DDL: criação das tabelas =====

-- (1) ddd_user
CREATE TABLE ddd_user(
    id_user NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_USER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(50) NOT NULL UNIQUE,
    senha VARCHAR2(100) NOT NULL
);

-- (2) ddd_trilha
CREATE TABLE ddd_trilha (
    id_tri NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_TRILHA PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL,
    dificuldade VARCHAR2(20) NOT NULL CHECK (dificuldade IN ('facil', 'medio', 'dificil')),
    descricao VARCHAR2(100) NOT NULL
);

-- (3) ddd_modulo
CREATE TABLE ddd_modulo (
    id_mod NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_MODULO PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    duracao VARCHAR2(10) NOT NULL,
    link VARCHAR2(255) NOT NULL,
    id_tri NUMBER(5) NOT NULL,
    CONSTRAINT FK_MODULO_TRILHA FOREIGN KEY (id_tri) REFERENCES ddd_trilha(id_tri) ON DELETE CASCADE
);

-- (4) ddd_prog
CREATE TABLE ddd_prog (
    id_prog NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_PROG PRIMARY KEY,
    status NUMBER(3) NOT NULL CHECK (status BETWEEN 0 AND 100),
    id_user NUMBER(5) NOT NULL,
    id_mod NUMBER(5) NOT NULL,
    CONSTRAINT FK_PROG_USER FOREIGN KEY (id_user) REFERENCES ddd_user(id_user) ON DELETE CASCADE,
    CONSTRAINT FK_PROG_MODULO FOREIGN KEY (id_mod) REFERENCES ddd_modulo(id_mod) ON DELETE CASCADE,
    CONSTRAINT UQ_PROG_USER_MODULO UNIQUE (id_user, id_mod)
);

-- (5) ddd_sugs
CREATE TABLE ddd_sugs (
    id_sugs NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_SUGS PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    descricao VARCHAR2(100) NOT NULL,
    duracao VARCHAR2(20) NOT NULL,
    dificuldade VARCHAR2(20) NOT NULL CHECK (dificuldade IN ('facil', 'medio', 'dificil')),
    link VARCHAR2(255) NOT NULL
);

-- (6) ddd_trilha_pers
CREATE TABLE ddd_trilha_pers (
    id_pers NUMBER(5) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_DDD_TRILHA_PERS PRIMARY KEY,
    id_user NUMBER(5) NOT NULL,
    data_criacao DATE DEFAULT SYSDATE,
    json_conteudo CLOB,
    CONSTRAINT FK_TRILHA_PERS_USER FOREIGN KEY (id_user) REFERENCES ddd_user(id_user) ON DELETE CASCADE
);

-- Índice para otimizar buscas.
CREATE INDEX idx_modulo_trilha ON ddd_modulo(id_tri);
CREATE INDEX idx_trilha_pers_user ON ddd_trilha_pers(id_user);
CREATE INDEX idx_progresso_user ON ddd_prog(id_user);
CREATE INDEX idx_progresso_modulo ON ddd_prog(id_mod);

-- SELECTs
SELECT * FROM ddd_user;
SELECT * FROM ddd_trilha;
SELECT * FROM ddd_modulo;
SELECT * FROM ddd_prog;
SELECT * FROM ddd_sugs;
SELECT * FROM ddd_trilha_pers;